[workspace]
authors = ["Gian <gian.cercena@greenmountainpower.com>"]
channels = ["conda-forge"]
name = "AdventofCode"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
tqdm = ">=4.67.1,<5"
numpy = ">=2.3.5,<3"
scikit-learn = ">=1.7.2,<2"
matplotlib = ">=3.10.8,<4"
networkx = ">=3.6.1,<4"
